project_name: pss
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/s3driver/main.go
    id: "s3driver"
    binary: s3driver
    goos:
      - linux
    goarch:
      - amd64
#    flags:
#      - trimpath
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-extldflags "-static" -X main.version={{ .Version }} -X main.commit={{ .Branch }}@{{ .ShortCommit }} -X main.buildTime={{ .Date }} -X main.builtBy=CI'
dockers:
  - image_templates: ["ghcr.io/habakke/csi-s3:{{ .Version }}", "ghcr.io/habakke/csi-s3:latest"]
    ids: [s3driver]
    goos: linux
    goarch: amd64
    dockerfile: ./cmd/s3driver/Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=K8S CSI S3 Driver
      - --label=org.opencontainers.image.url=https://github.com/habakke/csi-s3
      - --label=org.opencontainers.image.source=https://github.com/habakke/csi-s3
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates: ["ghcr.io/habakke/csi-s3:{{ .Version }}-full", "ghcr.io/habakke/csi-s3:full"]
    ids: [s3driver]
    goos: linux
    goarch: amd64
    dockerfile: ./cmd/s3driver/Dockerfile.full
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=K8S CSI S3 Driver
      - --label=org.opencontainers.image.url=https://github.com/habakke/csi-s3
      - --label=org.opencontainers.image.source=https://github.com/habakke/csi-s3
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
release:
  disable: true
changelog:
  skip: true
