project_name: csi-s3
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/s3driver/main.go
    id: s3driver
    binary: s3driver
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-extldflags "-static" -X main.version={{ .Version }} -X main.commit={{ .Branch }}@{{ .ShortCommit }} -X main.buildTime={{ .Date }} -X main.builtBy=CI'
docker_manifests:
  - name_template: "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}-amd64"
  - name_template: "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}"
    image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}-amd64"
  - name_template: "ghcr.io/habakke/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:latest-amd64"
dockers:
  - image_templates:
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/habakke/{{ .ProjectName }}:{{ .Env.GITHUB_SHA }}-amd64"
      - "ghcr.io/habakke/{{ .ProjectName }}:latest-amd64"
    ids: [s3driver]
    goos: linux
    goarch: amd64
    dockerfile: ./cmd/s3driver/Dockerfile
    use_buildx: true
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=K8S CSI S3 Driver
      - --label=org.opencontainers.image.source=https://github.com/habakke/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
release:
  disable: true
changelog:
  skip: true
