apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: static-s3-bucket
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: new-pv